"""RAS-MortDB MCP server: tools generated by Paper2Agent from https://github.com/PA-RRanjan/RAS-MortDB.

Paper: Ranjan et al., "Does YOLO26 Truly Offer Advantages over Its Predecessors for Edge Deployment?
A Benchmark Study in Aquaculture", AI 2026, 7(9), 354. https://doi.org/10.3390/ai7090354
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from fastmcp import FastMCP  # noqa: E402
from tools.run_inference import run_inference_mcp  # noqa: E402

mcp = FastMCP(name="RAS-MortDB")
mcp.mount(run_inference_mcp)

if __name__ == "__main__":
    mcp.run()
